// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var base_url, bio, f, get_files_directory, get_iframed_document, isNumber, local_element_viewer, local_url, overlay_controller, pdf, pdfs, remote_element_viewer, remote_web_viewer, sb,
      _this = this;
    console.log(JSON.stringify({
      name: "My Web App",
      main: 'index.html'
    }));
    isNumber = function(n) {
      return !isNaN(parseFloat(n)) && isFinite(n);
    };
    get_iframed_document = function(selector) {
      return $(selector)[0].contentWindow;
    };
    base_url = document.URL.replace('index.html', '');
    get_files_directory = function() {
      return base_url + 'files/Biologia/120.xod';
    };
    remote_element_viewer = document.getElementById('remote_viewer');
    local_element_viewer = document.getElementById('local_viewer');
    local_url = document.URL;
    overlay_controller = new OverlayController($('#remote_viewer'));
    sb = new ScreenBlocker($('#wrapper'));
    f = function(e, d) {
      var doc;
      doc = get_iframed_document('#remote_viewer iframe');
      doc.readerControl.docViewer.SetLinkReadyCallback(function(linkElement, link) {
        return linkElement.onclick = function() {
          return overlay_controller.create_iframe(link);
        };
      });
      sb.unblock();
      return new ScreenFitter('.pdf_viewer', {
        container: $(window),
        onResize: overlay_controller.update_overlay_dimensions
      });
    };
    $(window).bind('documentLoaded', f);
    pdfs = {
      '1': 'MWNiYmRhYmUtZmZmMy00OTBlLWJhN2ItODI3ODQ3Nzk4OTRk',
      '2': 'ZDljMzU3OGEtNmE5YS00NzUzLWIxN2MtZGEwYTE4NDgxNTVm'
    };
    pdf = pdfs['1'];
    bio = get_files_directory();
    return remote_web_viewer = new PDFTron.WebViewer({
      initialDoc: bio,
      type: 'html5,html5Mobile',
      enableAnnotations: true,
      cloudApiId: pdf,
      path: "js/pdf/",
      serverUrl: ''
    }, remote_element_viewer);
  });

}).call(this);
