// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var PdfViewerArgs;
    new Reloader();
    setup_urls();
    PdfViewerArgs = {
      viewer_element_id: 'remote_viewer'
    };
    if (is_app()) {
      return new LocalPdfViewer(PdfViewerArgs);
    } else {
      return new RemotePdfViewer(PdfViewerArgs);
    }
  });

}).call(this);
