// Generated by CoffeeScript 1.4.0
(function() {

  this.JSV = {
    menu: {
      main: function(structure) {
        var s, _i, _len, _outstream;
        _outstream = "                     <console class=\"log structure\">                       </console>                       <ul class=\"menu\">                       </ul>";
        for (_i = 0, _len = structure.length; _i < _len; _i++) {
          s = structure[_i];
          _outstream += "  <li class=\"menu_item\"> " + s + "                           </li>";
        }
        return _outstream;
      }
    },
    make_args: function(a) {
      return escape(JSON.stringify(a));
    },
    parse_args: function(a) {
      return JSON.parse(unescape(a));
    },
    set_args: function(a) {
      return JSV.args = a;
    },
    set_parse_args: function(a) {
      var _a;
      _a = JSV.parse_args(a);
      JSV.set_args(_a);
      return _a;
    },
    wrap: function(map, template) {
      var content, html, placeholder;
      if (typeof map === 'string') {
        map = {
          __placeholder__: map
        };
      }
      html = template;
      for (placeholder in map) {
        content = map[placeholder];
        html = html.replace(placeholder, content);
      }
      return html;
    },
    empty: function() {}
  };

}).call(this);
