// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.LocalPdfViewer = (function(_super) {

    __extends(LocalPdfViewer, _super);

    function LocalPdfViewer(args) {
      this.args = args;
      LocalPdfViewer.__super__.constructor.call(this, this.args);
      this.current_pdf = get_files_directory();
      this.view(this.current_pdf);
    }

    LocalPdfViewer.prototype.view = function(current_pdf) {
      this.current_pdf = current_pdf;
      this.web_viewer_arguments.initialDoc = this.current_pdf;
      return this.web_viewer_instance = new PDFTron.WebViewer(this.web_viewer_arguments, this.viewer_element);
    };

    return LocalPdfViewer;

  })(PdfViewer);

}).call(this);
