// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.OverlayController = (function() {

    function OverlayController(container) {
      this.container = container;
      this.set_dimensions = __bind(this.set_dimensions, this);

      this.update_overlay_dimensions = __bind(this.update_overlay_dimensions, this);

      this.overlays = [];
      this.set_dimensions(this.container);
    }

    OverlayController.prototype.update_overlay_dimensions = function() {
      var overlay, _i, _len, _ref, _results;
      this.set_dimensions();
      _ref = this.overlays;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        overlay = _ref[_i];
        _results.push(overlay.resize(this.dimensions));
      }
      return _results;
    };

    OverlayController.prototype.set_dimensions = function(obj) {
      var offset;
      if (obj == null) {
        obj = this.container;
      }
      offset = obj.offset();
      return this.dimensions = {
        width: obj.width(),
        height: this.container.height(),
        offset: offset
      };
    };

    OverlayController.prototype.create_iframe = function(link) {
      var overlay;
      this.set_dimensions(this.container);
      overlay = new iFrameOverlay(this.container, this.dimensions, link, this);
      return this.overlays.push(overlay);
    };

    return OverlayController;

  })();

}).call(this);
