// Generated by CoffeeScript 1.4.0
(function() {

  this.OverlayToolBar = (function() {

    function OverlayToolBar(element, controller) {
      this.create_markup();
      this.assign_actions();
    }

    OverlayToolBar.prototype.create_markup = function() {};

    return OverlayToolBar;

  })();

}).call(this);
