// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.PdfViewer = (function() {

    function PdfViewer(args) {
      this.args = args;
      this.on_document_load = __bind(this.on_document_load, this);

      $(window).bind('documentLoaded', this.on_document_load);
      this.viewer_element = document.getElementById(this.args.viewer_element_id);
      this.before_document_load();
      this.web_viewer_arguments = {
        type: 'html5,html5Mobile',
        enableAnnotations: true,
        path: 'js/pdf',
        config: 'js/pdf_viewer_configuration.js',
        serverUrl: ''
      };
    }

    PdfViewer.prototype.on_document_load = function(e, d) {
      var doc, overlay_controller,
        _this = this;
      doc = get_iframed_document('#remote_viewer iframe');
      overlay_controller = this.overlay_controller;
      doc.readerControl.docViewer.SetLinkReadyCallback(function(linkElement, link) {
        return linkElement.onclick = function() {
          return overlay_controller.create_iframe(link);
        };
      });
      this.screen_blocker.unblock();
      return new ScreenFitter('.pdf_viewer', {
        container: $(window),
        on_resize: overlay_controller.update_overlay_dimensions,
        strategy: 'match_screen'
      });
    };

    PdfViewer.prototype.before_document_load = function() {
      this.overlay_controller = new OverlayController($('#remote_viewer'), base_url + 'files/ObjTest/');
      return this.screen_blocker = new ScreenBlocker($('#wrapper'), {
        img_src: 'img/everywhere-logo.png',
        img_width: 210,
        img_height: 65
      });
    };

    return PdfViewer;

  })();

}).call(this);
