// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.Reloader = (function() {

    function Reloader() {
      this.key_up = __bind(this.key_up, this);

      this.key_down = __bind(this.key_down, this);
      $(document).keydown(this.key_down);
      $(document).keyup(this.key_up);
      this.is_e_down = false;
      this.is_z_down = false;
    }

    Reloader.prototype.key_down = function(e) {
      if (e.keyCode === 69) {
        this.is_e_down = true;
      }
      if (e.keyCode === 90) {
        this.is_z_down = true;
      }
      if (e.keyCode === 82 && this.is_e_down && this.is_z_down) {
        console.log('Reloading...');
        return Reloader.reload();
      }
    };

    Reloader.reload = function() {
      return window.location.reload();
    };

    Reloader.prototype.key_up = function(e) {
      if (e.keyCode === 69) {
        this.is_e_down = false;
      }
      if (e.keyCode === 90) {
        return this.is_z_down = true;
      }
    };

    return Reloader;

  })();

}).call(this);
