// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.RemotePdfViewer = (function(_super) {

    __extends(RemotePdfViewer, _super);

    function RemotePdfViewer(args) {
      this.args = args;
      RemotePdfViewer.__super__.constructor.call(this, this.args);
      this.default_pdf = 'NzliNjNlMmMtYTBlNi00NmE1LWI0NGMtZTJjN2JhNTlhNzUy';
      this.current_pdf = window._get['pdf'] || this.default_pdf;
      this.view(this.current_pdf);
    }

    RemotePdfViewer.prototype.view = function(current_pdf) {
      this.current_pdf = current_pdf;
      this.web_viewer_arguments.cloudApiId = this.current_pdf;
      return this.web_viewer_instance = new PDFTron.WebViewer(this.web_viewer_arguments, this.viewer_element);
    };

    return RemotePdfViewer;

  })(PdfViewer);

}).call(this);
