// Generated by CoffeeScript 1.4.0
(function() {

  this.ScreenBlocker = (function() {

    function ScreenBlocker(target, args) {
      this.target = target;
      this.args = args != null ? args : {};
      this.block();
      this.target.css('opacity', '0');
    }

    ScreenBlocker.prototype.unblock = function() {
      this.blocker.remove();
      return this.target.css('opacity', '1');
    };

    ScreenBlocker.prototype.block = function() {
      this.create_blocker();
      return this.target.after(this.blocker);
    };

    ScreenBlocker.prototype.create_blocker = function() {
      var name, value, _ref, _results;
      this.blocker = $('<div class="screen_blocker"></div>');
      if (this.args.custom_css != null) {
        _ref = this.args.custom_css;
        _results = [];
        for (name in _ref) {
          value = _ref[name];
          _results.push(this.blocker.css(name, value));
        }
        return _results;
      }
    };

    return ScreenBlocker;

  })();

}).call(this);
