// Generated by CoffeeScript 1.4.0
(function() {

  this.StructuredMenu = (function() {

    function StructuredMenu() {
      $('#menu').html(JSV.menu.main(this.get_menu_structure()));
    }

    StructuredMenu.prototype.get_menu_structure = function() {
      return ['Biologia', 'Física', 'Matemática', 'Português', 'Química'];
    };

    return StructuredMenu;

  })();

}).call(this);
