// Generated by CoffeeScript 1.4.0
(function() {

  this.change_vendor_behaviour = function(doc) {
    var dafuq;
    this.sidePanel = doc.readerControl.$thumbnailViewContainer.parents('#sidePanel');
    dafuq = {
      "transition": "none !important",
      "-moz-transition": "none !important",
      "-webkit-transition": "none !important",
      "-o-transition": "none !important",
      "-ms-transition": "none !important"
    };
    return this.sidePanel.css(dafuq);
  };

}).call(this);
