var d=!0,h=null,l=!1;function p(){return function(){}}var q=self,C=q.qf;(function(){function a(a){c?c.push(a):setTimeout(a,0)}var b={version:"0.7.2.0",yg:function(a){return void 0===a},xg:function(a){return a===h},ma:function(a){return a===h||void 0===a},zg:function(a){return a!==h&&void 0!==a}},c=[];q.attachEvent&&q.attachEvent("onload",function(){if(c){var a=c;c=h;for(var b=0,e=a.length;b<e;b++)a[b]()}});C||(q.qf=C={Na:a,Ig:a});for(var e in b)C[e]=b[e]})();Object.Z="Object";Object.za=h;
Object.$f=function(a){for(var b in a)delete a[b]};Object.Ld=function(a,b){return void 0!==a[b]};Object.keys?Object.ff=function(a){return Object.keys(a).length}:(Object.keys=function(a){var b=[],c;for(c in a)b.push(c);return b},Object.ff=function(a){var b=0,c;for(c in a)b++;return b});Boolean.Z="Boolean";Boolean.parse=function(a){return"true"==a.toLowerCase()};Number.Z="Number";
Number.parse=function(a){return!a||!a.length?0:0<=a.indexOf(".")||0<=a.indexOf("e")||(1>a.length?0:"f"==a.substr(a.length-1))||(1>a.length?0:"F"==a.substr(a.length-1))?parseFloat(a):parseInt(a,10)};Number.prototype.La=function(a){return C.ma(a)||0==a.length||"i"==a?this.toString():E(this,a,l)};Number.prototype.Nd=function(a){return C.ma(a)||0==a.length||"i"==a?this.toLocaleString():E(this,a,d)};
Number.kc=function(a,b,c,e){var f=h;c=a.indexOf(c);0<c&&(f=a.substr(c),a=a.substr(0,c));(c=N(a,"-"))&&(a=a.substr(1));var g=0,k=b[g];if(a.length<k)return f?a+f:a;for(var n=a.length,m="",s=l;!s;){var w=k,x=n-w;0>x&&(k+=x,w+=x,x=0,s=d);if(!w)break;x=a.substr(x,w);m=m.length?x+e+m:x;n-=w;g<b.length-1&&(g++,k=b[g])}c&&(m="-"+m);return f?m+f:m};
function E(a,b,c){c=c?C.Td.Af.nf:C.Td.Bf.nf;var e="",f=-1;1<b.length&&(f=parseInt(b.substr(1)));b=b.charAt(0);switch(b){case "d":case "D":e=parseInt(Math.abs(a)).toString();-1!=f&&(e=R(e,f));0>a&&(e="-"+e);break;case "x":case "X":e=parseInt(Math.abs(a)).toString(16);"X"==b&&(e=e.toUpperCase());-1!=f&&(e=R(e,f));break;case "e":case "E":e=-1==f?a.toExponential():a.toExponential(f);"E"==b&&(e=e.toUpperCase());break;case "f":case "F":case "n":case "N":-1==f&&(f=c.Ag);e=a.toFixed(f).toString();f&&"."!=
c.Qd&&(f=e.indexOf("."),e=e.substr(0,f)+c.Qd+e.substr(f+1));if("n"==b||"N"==b)e=Number.kc(e,c.Cg,c.Qd,c.Bg);break;case "c":case "C":-1==f&&(f=c.dg);e=Math.abs(a).toFixed(f).toString();f&&"."!=c.Fd&&(f=e.indexOf("."),e=e.substr(0,f)+c.Fd+e.substr(f+1));e=Number.kc(e,c.fg,c.Fd,c.eg);e=0>a?String.La(c.gg,e):String.La(c.hg,e);break;case "p":case "P":-1==f&&(f=c.Dg),e=(100*Math.abs(a)).toFixed(f).toString(),f&&"."!=c.Rd&&(f=e.indexOf("."),e=e.substr(0,f)+c.Rd+e.substr(f+1)),e=Number.kc(e,c.Fg,c.Rd,c.Eg),
e=0>a?String.La(c.Gg,e):String.La(c.Hg,e)}return e}String.Z="String";String.Ud="";String.$e=function(a,b,c){c&&(a&&(a=a.toUpperCase()),b&&(b=b.toUpperCase()));a=a||"";b=b||"";return a==b?0:a<b?-1:1};String.concat=function(){return 2===arguments.length?arguments[0]+arguments[1]:Array.prototype.join.call(arguments,"")};String.jg=function(a,b,c){return 0==String.$e(a,b,c)};
String.ed=function(a,b,c){String.fd||(String.fd=/(\{[^\}^\{]+\})/g);return a.replace(String.fd,function(a,f){var g=b[parseInt(f.substr(1))+1];if(C.ma(g))return"";if(g.La){var k=h,n=f.indexOf(":");0<n&&(k=f.substring(n+1,f.length-1));return c?g.Nd(k):g.La(k)}return c?g.toLocaleString():g.toString()})};String.La=function(a){return String.ed(a,arguments,l)};String.cf=function(a,b){for(var c=a,e=1;e<b;e++)c+=a;return c};String.kf=function(a){return!a||!a.length};
String.Nd=function(a){return String.ed(a,arguments,d)};function R(a,b){return a.length<b?String.cf("0",b-a.length)+a:a}String.prototype.remove=function(a,b){return!b||a+b>this.length?this.substr(0,a):this.substr(0,a)+this.substr(a+b)};function N(a,b){return!b.length?d:b.length>a.length?l:a.substr(0,b.length)==b}String.prototype.trim||(String.prototype.trim=function(){return this.replace(/\s*$/,"").replace(/^\s*/,"")});Array.Z="Array";Array.Hb=[C.Fb];
Array.prototype.add=function(a){this[this.length]=a};Array.prototype.Bc=function(){return 1===this.length?[this[0]]:Array.apply(h,this)};Array.prototype.contains=function(a){return 0<=this.indexOf(a)};function U(a){return a.length?a[a.Pf?0:a.length-1]:h}Array.prototype.every||(Array.prototype.every=function(a,b){for(var c=this.length,e=0;e<c;e++)if(e in this&&!a.call(b,this[e],e,this))return l;return d});
Array.prototype.filter||(Array.prototype.filter=function(a,b){for(var c=this.length,e=[],f=0;f<c;f++)if(f in this){var g=this[f];a.call(b,g,f,this)&&e.push(g)}return e});Array.prototype.forEach||(Array.prototype.forEach=function(a,b){for(var c=this.length,e=0;e<c;e++)e in this&&a.call(b,this[e],e,this)});Array.prototype.Ma=function(){return new C.Db(this)};Array.prototype.index=function(a,b){for(var c=this.length,e={},f=0;f<c;f++)if(f in this){var g=a.call(b,this[f],f);String.kf(g)||(e[g]=this[f])}return e};
Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){var c=this.length;if(c)for(var e=b||0;e<c;e++)if(this[e]===a)return e;return-1});Array.prototype.map||(Array.prototype.map=function(a,b){for(var c=this.length,e=Array(c),f=0;f<c;f++)f in this&&(e[f]=a.call(b,this[f],f,this));return e});Array.parse=function(a){return eval("("+a+")")};Array.prototype.remove=function(a){a=this.indexOf(a);return 0<=a?(this.splice(a,1),d):l};Array.prototype.Ec=function(a){this.splice(a,1)};
Array.prototype.some||(Array.prototype.some=function(a,b){for(var c=this.length,e=0;e<c;e++)if(e in this&&a.call(b,this[e],e,this))return d;return l});Array.sf=function(a){return Array.prototype.slice.call(a)};RegExp.Z="RegExp";RegExp.parse=function(a){if(N(a,"/")){var b=a.lastIndexOf("/");if(1<b)return RegExp(a.substring(1,b),a.substr(b+1))}return h};Error.Z="Error";
Error.bg=function(a,b,c){a=Error(a);if(b)for(var e in b)a[e]=b[e];c&&(a.pg=c);if(!C.ma(a.stack)&&!C.ma(a.fileName)&&!C.ma(a.lineNumber)){b=a.stack.split("\n");c=b[0];for(e=a.fileName+":"+a.lineNumber;!C.ma(c)&&-1===c.indexOf(e);)b.shift(),c=b[0];c=b[1];isNullOrUndefined(c)||(c=c.match(/@(.*):(\d+)$/),C.ma(c)||(b.shift(),a.stack=b.join("\n"),a.fileName=c[1],a.lineNumber=parseInt(c[2])))}return a};C.ha=q.ha||p();C.ha.Z="Debug";
C.ha.writeln||(C.ha.writeln=function(a){q.console?q.console.debug?q.console.debug(a):q.console.log&&q.console.log(a):q.opera&&q.opera.postError&&q.opera.postError(a)});C.ha.dd=function(a){C.ha.writeln(a);eval("debugger;")};C.ha.assert=function(a,b){a||(b="Assert failed: "+b,confirm(b+"\r\n\r\nBreak into debugger?")&&C.ha.dd(b))};C.ha.kg=function(a){C.ha.dd(a)};q.w=Function;q.w.Z="Type";q.Nc=function(a){this.Z=a};q.Nc.prototype={ee:d};
q.w.of=function(){q.hc||(q.hc={});q.Rc||(q.Rc=[]);if(!q.hc.trn){for(var a=self,b=["trn"],c=0;c<b.length;c++){var e=b[c],f=a[e];f||(a[e]=f=new q.Nc(b.slice(0,c+1).join(".")),0==c&&q.Rc.add(f));a=f}q.hc.trn=a}};q.w.prototype.M=function(a,b,c){this.prototype.constructor=this;this.Z=a;this.Oc=d;this.za=b||Object;b&&(this.Gb=d);if(c){this.Hb=[];for(var e=2;e<arguments.length;e++)c=arguments[e],this.Hb.add(c)}};function V(a,b){a.Z=b;a.Qc=d}
q.w.prototype.Fc=function(){if(this.Gb){var a=this.za;a.Gb&&a.Fc();for(var b in a.prototype){var c=a.prototype[b];this.prototype[b]||(this.prototype[b]=c)}delete this.Gb}};q.w.prototype.pf||(q.w.prototype.pf=q.w.prototype.Fc);function X(a,b){return C.ma(b)?l:a==Object||b instanceof a?d:aa(a,q.w.ef(b))}
function aa(a,b){if(a==Object||a==b)return d;if(a.Oc)for(var c=b.za;c;){if(a==c)return d;c=c.za}else if(a.Qc){var e=b.Hb;if(e&&e.contains(a))return d;for(c=b.za;c;){if((e=c.Hb)&&e.contains(a))return d;c=c.za}}return l}q.w.rg=function(a){return a.Oc==d};q.w.tg=function(a){return a.de==d};q.w.ug=function(a){return a.de==d&&a.Pc==d};q.w.vg=function(a){return a.Qc==d};q.w.wg=function(a){return a.ee==d};q.w.Yf=function(a,b){return X(b,a)};q.w.Kg=function(a,b){return X(b,a)?a:h};
q.w.ef=function(a){var b=h;try{b=a.constructor}catch(c){}if(!b||!b.Z)b=Object;return b};q.w.hf=function(a){if(!a)return h;q.w.ic||(q.w.ic={});var b=q.w.ic[a];b||(b=eval(a),q.w.ic[a]=b);return b};q.w.parse=function(a){return q.w.hf(a)};C.fc=p();C.fc.M("Enum");
C.fc.parse=function(a,b){var c=a.prototype;if(a.Pc){for(var e=b.split("|"),f=0,g=d,k=e.length-1;0<=k;k--){var n=e[k].trim(),m=l;for(s in c)if(s===n){f|=c[s];m=d;break}if(!m){g=l;break}}if(g)return f}else for(var s in c)if(s===b)return c[s];throw"Invalid Enumeration Value";};
C.fc.Gf=function(a){var b=this.prototype;if(!this.Pc||0===a){for(var c in b)if(b[c]===a)return c;throw"Invalid Enumeration Value";}var e=[];for(c in b)b[c]&a&&(e.length&&e.add(" | "),e.add(c));if(!e.length)throw"Invalid Enumeration Value";return e.join("")};C.G=p();C.G.M("Delegate");C.G.empty=p();C.G.he=function(a,b,c){for(var e=0;e<a.length;e+=2)if(a[e]===b&&a[e+1]===c)return d;return l};
C.G.lc=function(a){function b(){if(2==a.length)return a[1].apply(a[0],arguments);for(var c=a.Bc(),b=0;b<c.length;b+=2)C.G.he(a,c[b],c[b+1])&&c[b+1].apply(c[b],arguments);return h}b.la=a;return b};C.G.create=function(a,b){return!a?b:C.G.lc([a,b])};C.G.ag=function(a,b){return!a?!b.la?C.G.create(h,b):b:!b?!a.la?C.G.create(h,a):a:C.G.lc((a.la?a.la:[h,a]).concat(b.la?b.la:[h,b]))};
C.G.remove=function(a,b){if(!a||a===b)return h;if(!b)return a;var c=a.la,e=h,f;b.la?(e=b.la[0],f=b.la[1]):f=b;for(var g=0;g<c.length;g+=2)if(c[g]===e&&c[g+1]===f){if(2==c.length)return h;c.splice(g,2);return C.G.lc(c)}return a};C.G.cg=function(a,b,c){c=c||"__"+(new Date).valueOf();self[c]=b?a:function(){try{delete self[c]}catch(b){self[c]=void 0}a.apply(h,arguments)};return c};C.G.ig=function(a){delete self[a]};C.G.Zf=function(a){self[a]=C.G.empty};C.gb=p();C.gb.prototype={Od:h};
C.gb.Ma=function(a){return a?a.Ma?a.Ma():new C.Db(a):h};V(C.gb,"IEnumerator");C.Fb=p();C.Fb.prototype={Ma:h};V(C.Fb,"IEnumerable");C.Db=function(a){this.Sc=a;this.Da=-1;this.Gd=h};C.Db.prototype={Od:function(){this.Da++;this.Gd=this.Sc[this.Da];return this.Da<this.Sc.length}};C.Db.M("ArrayEnumerator",h,C.gb);C.Kc=p();C.Kc.prototype={bf:h};V(C.Kc,"IDisposable");C.Mc=function(a){this.zd=!C.ma(a)?[a]:[];this.sg=0==this.zd.length};C.Mc.prototype={toString:function(a){return this.zd.join(a||"")}};C.Mc.M("StringBuilder");
C.Eb=p();C.Eb.M("EventArgs");C.Eb.Ud=new C.Eb;q.XMLHttpRequest||(q.XMLHttpRequest=function(){for(var a=["Msxml2.XMLHTTP","Microsoft.XMLHTTP"],b=0;b<a.length;b++)try{return new ActiveXObject(a[b])}catch(c){}return h});C.Jc=function(){var a=C.Jc;a.Gb&&a.Fc();a.za.apply(this);this.cancel=l};C.Jc.M("CancelEventArgs",C.Eb);C.be=function(a,b,c){this.mg=a;this.Lg=b;3==arguments.length&&(this.Mg=c)};C.be.M("Tuple");C.Y=function(a){this.Sf=a;this.ub=h};C.Y.prototype={};C.Y.yc=[];C.Y.Me={bf:function(){C.Y.yc.pop()}};
C.Y.Jg=function(a){C.Y.yc.push(a);return C.Y.Me};C.Y.fe=function(a){var b=C.Y.yc,c=b.length;if(c){a=a||[];for(var e=0;e<c;e++){var f=b[e];a.contains(f)||a.push(f)}return a}return h};C.Y.Ge=function(a){for(var b=0,c=a.length;b<c;b++)a[b].qg()};C.Y.M("Observable");C.Lc=function(a){this.Fa=a||[];this.ub=h};
C.Lc.prototype={add:function(a){this.Fa.push(a);Y(this)},contains:function(a){return this.Fa.contains(a)},Ma:function(){this.ub=C.Y.fe(this.ub);return this.Fa.Ma()},indexOf:function(a){return this.Fa.indexOf(a)},remove:function(a){return this.Fa.remove(a)?(Y(this),d):l},Ec:function(a){this.Fa.Ec(a);Y(this)},sf:function(){return this.Fa}};function Y(a){var b=a.ub;b&&(a.ub=h,C.Y.Ge(b))}C.Lc.M("ObservableCollection",h,C.Fb);C.Vd=p();V(C.Vd,"IApplication");C.Wd=p();V(C.Wd,"IContainer");C.Zd=p();
V(C.Zd,"IObjectFactory");C.Xd=p();V(C.Xd,"IEventManager");C.Yd=p();V(C.Yd,"IInitializable");(function(a){function b(a,b,f,g,k,n){this.ya=16;this.ae=288;this.status=0;this.root=h;this.pa=0;var m=Array(this.ya+1),s,z,H,v,t,u,I,J=Array(this.ya+1),G,F,D,A=new c,O=Array(this.ya);v=Array(this.ae);var B,K=Array(this.ya+1),L,M,P;P=this.root=h;for(t=0;t<m.length;t++)m[t]=0;for(t=0;t<J.length;t++)J[t]=0;for(t=0;t<O.length;t++)O[t]=h;for(t=0;t<v.length;t++)v[t]=0;for(t=0;t<K.length;t++)K[t]=0;s=256<b?a[256]:this.ya;G=a;F=0;t=b;do m[G[F]]++,F++;while(0<--t);if(m[0]==b)this.root=h,this.status=this.pa=
0;else{for(u=1;u<=this.ya&&0==m[u];u++);I=u;n<u&&(n=u);for(t=this.ya;0!=t&&0==m[t];t--);H=t;n>t&&(n=t);for(L=1<<u;u<t;u++,L<<=1)if(0>(L-=m[u])){this.status=2;this.pa=n;return}if(0>(L-=m[t]))this.status=2,this.pa=n;else{m[t]+=L;K[1]=u=0;G=m;F=1;for(D=2;0<--t;)K[D++]=u+=G[F++];G=a;t=F=0;do if(0!=(u=G[F++]))v[K[u]++]=t;while(++t<b);b=K[H];K[0]=t=0;G=v;F=0;v=-1;B=J[0]=0;D=h;for(M=0;I<=H;I++)for(a=m[I];0<a--;){for(;I>B+J[1+v];){B+=J[1+v];v++;M=(M=H-B)>n?n:M;if((z=1<<(u=I-B))>a+1){z-=a+1;for(D=I;++u<M&&
!((z<<=1)<=m[++D]);)z-=m[D]}B+u>s&&B<s&&(u=s-B);M=1<<u;J[1+v]=u;D=Array(M);for(z=0;z<M;z++)D[z]=new c;P=P==h?this.root=new e:P.next=new e;P.next=h;P.list=D;O[v]=D;0<v&&(K[v]=t,A.fa=J[v],A.ca=16+u,A.Oa=D,u=(t&(1<<B)-1)>>B-J[v],O[v-1][u].ca=A.ca,O[v-1][u].fa=A.fa,O[v-1][u].na=A.na,O[v-1][u].Oa=A.Oa)}A.fa=I-B;F>=b?A.ca=99:G[F]<f?(A.ca=256>G[F]?16:15,A.na=G[F++]):(A.ca=k[G[F]-f],A.na=g[G[F++]-f]);z=1<<I-B;for(u=t>>B;u<M;u+=z)D[u].ca=A.ca,D[u].fa=A.fa,D[u].na=A.na,D[u].Oa=A.Oa;for(u=1<<I-1;0!=(t&u);u>>=
1)t^=u;for(t^=u;(t&(1<<B)-1)!=K[v];)B-=J[v],v--}this.pa=J[1];this.status=0!=L&&1!=H?1:0}}}function c(){this.na=this.fa=this.ca=0;this.Oa=h}function e(){this.list=this.next=h}var f=[0,1,3,7,15,31,63,127,255,511,1023,2047,4095,8191,16383,32767,65535],g=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258,0,0],k=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0,99,99],n=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,
8193,12289,16385,24577],m=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13],s=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15];a.Sa||(a.Sa={});a.Sa.gc=function(a){this.yf();this.dc=a;this.ec=0};a.Sa.gc.prototype={Id:function(a){for(var c,b=Array(1024),e=[],f=0;f<a&&0<(c=this.xf(b,0,b.length));)e[e.length]=String.fromCharCode.apply(h,b.slice(0,c)),f+=c;return f?(this.dc=this.dc.slice(this.ec),this.ec=0,e.join("")):""},tf:function(){return this.dc.length==this.ec?-1:this.dc.charCodeAt(this.ec++)&
255},C:function(a){for(;this.Pa<a;)this.fb|=this.tf()<<this.Pa,this.Pa+=8},F:function(a){return this.fb&f[a]},B:function(a){this.fb>>=a;this.Pa-=a},cc:function(a,c,b){var e,f,g;if(0==b)return 0;for(g=0;;){this.C(this.ga);f=this.xa.list[this.F(this.ga)];for(e=f.ca;16<e;){if(99==e)return-1;this.B(f.fa);e-=16;this.C(e);f=f.Oa[this.F(e)];e=f.ca}this.B(f.fa);if(16==e)this.P&=32767,a[c+g++]=this.wa[this.P++]=f.na;else{if(15==e)break;this.C(e);this.X=f.na+this.F(e);this.B(e);this.C(this.eb);f=this.Sd.list[this.F(this.eb)];
for(e=f.ca;16<e;){if(99==e)return-1;this.B(f.fa);e-=16;this.C(e);f=f.Oa[this.F(e)];e=f.ca}this.B(f.fa);this.C(e);this.Qa=this.P-f.na-this.F(e);for(this.B(e);0<this.X&&g<b;)this.X--,this.Qa&=32767,this.P&=32767,a[c+g++]=this.wa[this.P++]=this.wa[this.Qa++]}if(g==b)return b}this.va=-1;return g},zf:function(a,c,b){var e;e=this.Pa&7;this.B(e);this.C(16);e=this.F(16);this.B(16);this.C(16);if(e!=(~this.fb&65535))return-1;this.B(16);this.X=e;for(e=0;0<this.X&&e<b;)this.X--,this.P&=32767,this.C(8),a[c+e++]=
this.wa[this.P++]=this.F(8),this.B(8);0==this.X&&(this.va=-1);return e},wf:function(a,c,e){if(this.bc==h){var f,r=Array(288);for(f=0;144>f;f++)r[f]=8;for(;256>f;f++)r[f]=9;for(;280>f;f++)r[f]=7;for(;288>f;f++)r[f]=8;this.Ic=7;f=new b(r,288,257,g,k,this.Ic);if(0!=f.status)return alert("HufBuild error: "+f.status),-1;this.bc=f.root;this.Ic=f.pa;for(f=0;30>f;f++)r[f]=5;this.Hc=5;f=new b(r,30,0,n,m,this.Hc);if(1<f.status)return this.bc=h,alert("HufBuild error: "+f.status),-1;this.uf=f.root;this.Hc=f.pa}this.xa=
this.bc;this.Sd=this.uf;this.ga=this.Ic;this.eb=this.Hc;return this.cc(a,c,e)},vf:function(a,c,e){var f,r,S,T,W,z,H,v=Array(316);for(f=0;f<v.length;f++)v[f]=0;this.C(5);z=257+this.F(5);this.B(5);this.C(5);H=1+this.F(5);this.B(5);this.C(4);f=4+this.F(4);this.B(4);if(286<z||30<H)return-1;for(r=0;r<f;r++)this.C(3),v[s[r]]=this.F(3),this.B(3);for(;19>r;r++)v[s[r]]=0;this.ga=7;r=new b(v,19,19,h,h,this.ga);if(0!=r.status)return-1;this.xa=r.root;this.ga=r.pa;T=z+H;for(f=S=0;f<T;)if(this.C(this.ga),W=this.xa.list[this.F(this.ga)],
r=W.fa,this.B(r),r=W.na,16>r)v[f++]=S=r;else if(16==r){this.C(2);r=3+this.F(2);this.B(2);if(f+r>T)return-1;for(;0<r--;)v[f++]=S}else{17==r?(this.C(3),r=3+this.F(3),this.B(3)):(this.C(7),r=11+this.F(7),this.B(7));if(f+r>T)return-1;for(;0<r--;)v[f++]=0;S=0}this.ga=9;r=new b(v,z,257,g,k,this.ga);0==this.ga&&(r.status=1);if(0!=r.status)return-1;this.xa=r.root;this.ga=r.pa;for(f=0;f<H;f++)v[f]=v[f+z];this.eb=6;r=new b(v,H,0,n,m,this.eb);this.Sd=r.root;this.eb=r.pa;return 0==this.eb&&257<z||0!=r.status?
-1:this.cc(a,c,e)},yf:function(){this.wa==h&&(this.wa=Array(65536));this.Pa=this.fb=this.P=0;this.va=-1;this.ac=l;this.X=this.Qa=0;this.bc=this.xa=h},xf:function(a,c,b){var e,f;for(e=0;e<b&&!(this.ac&&-1==this.va);){if(0<this.X){if(0!=this.va)for(;0<this.X&&e<b;)this.X--,this.Qa&=32767,this.P&=32767,a[c+e++]=this.wa[this.P++]=this.wa[this.Qa++];else{for(;0<this.X&&e<b;)this.X--,this.P&=32767,this.C(8),a[c+e++]=this.wa[this.P++]=this.F(8),this.B(8);0==this.X&&(this.va=-1)}if(e==b)break}if(-1==this.va){if(this.ac)break;
this.C(1);0!=this.F(1)&&(this.ac=d);this.B(1);this.C(2);this.va=this.F(2);this.B(2);this.xa=h;this.X=0}switch(this.va){case 0:f=this.zf(a,c+e,b-e);break;case 1:f=this.xa!=h?this.cc(a,c+e,b-e):this.wf(a,c+e,b-e);break;case 2:f=this.xa!=h?this.cc(a,c+e,b-e):this.vf(a,c+e,b-e);break;default:f=-1}if(-1==f)return this.ac?0:-1;e+=f}return e}};a.Sa.og=function(c){return(new a.Sa.gc(c)).Id(4E7)}})(self);(function(a){function b(a){this.depth=this.index=0;this.v=a;this.location={start:0,Xb:1,Yb:1,end:a.length,empty:d};this.Bb=[this.location];this.Dc=l;"?"===this.v.charAt(1)&&this.Kd();this.location.empty=l}b.prototype={advance:function(){this.ua=h;this.Kd();var a=this.location.start;++a;this.location.empty=l;if("/"!==this.v.charAt(a))return this.location.empty="/"===this.v.charAt(this.v.indexOf(">",a)-1),d;this.location.end=d;return l},af:function(a){if(a)return a.split("&quot;").join('"').split("&lt;").join("<").split("&gt;").join(">").split("&amp;").join("&")},
Md:function(){var a=this.location.start+1,b=this.v.indexOf(">",a);this.location.empty&&--b;a=this.v.substring(a,b);this.ua={};b=a.indexOf(" ");if(-1!==b){this.Hd=a.substring(0,b);for(var a=a.slice(b),a=a.split('"'),b=a.length-1,f=0;f<b;++f){var g=a[f],k=a[++f];this.ua[g.substring(1,g.length-1)]=k}}else this.Hd=a},Kd:function(){if(this.Dc)this.Dc=l,this.location.start=this.v.indexOf("<",this.location.start+1);else{var a=this.location.Xb;if(!this.location.empty)for(var b=this.location.Yb;0<b;)a=this.v.indexOf("<",
a),"/"===this.v.charAt(++a)?--b:(a=this.v.indexOf(">",a),"/"!==this.v.charAt(a-1)&&++b);this.location.start=this.v.indexOf("<",a)}this.location.Xb=this.location.start+1;this.location.Yb=1},Zb:function(){this.v.Zb&&this.v.Zb(this.location.start)},A:function(){(this.ua===h||"undefined"===typeof this.ua)&&this.Md();return this.Hd},u:function(){++this.depth;this.location={start:this.location.start};this.Bb[this.Bb.length]=this.location;this.Dc=d},r:function(){--this.depth;this.ua=h;var a=this.location.Xb,
b=this.location.Yb,f=this.location.empty,g=this.location.end;this.Bb.pop();this.location=this.Bb[this.Bb.length-1];this.location.Xb=a;this.location.Yb=g?0:f?b:b+1},U:function(){return this.location.empty?d:"/"===this.v.charAt(this.v.indexOf("<",this.location)+1)},p:function(a){(this.ua===h||"undefined"===typeof this.ua)&&this.Md();return this.af(this.ua[a])}};a.ce=b})(self);q=self;self.w.of();q.trn.a=function(a){this.Wb=l;this.td=1E4;this.Ha={};this.$a=this.tb=0;this.z=[];this.ba=[];this.ba.add({});this.sb=0;this.c=a;this.xd=this.Cb("Width");this.wd=this.Cb("Height");this.z.push(q.trn.Ca.jf(this.xd,this.wd));this.O="c."+q.trn.a.d[q.trn.a.we]+"();";this.ja="c."+q.trn.a.d[q.trn.a.ve]+"();";this.V=l;this.b="";this.c.u();this.c.advance();a=this.c.A();q.trn.a.g(a,"FixedPage.Resources")&&(this.c.u(),this.c.advance(),this.Cd(),this.c.r());this.Ga=l};
q.trn.a.g=function(a,b){var c=q.trn.a.Ze;return a===b?d:a===c+b};q.trn.a.i=function(a){return q.trn.a.xb(a,3)};q.trn.a.yb=function(a){return a.split("\\").join("\\\\").split('"').join('\\"')};q.trn.a.xb=function(a,b){var c=b,e=Math.abs(a);0.5>e&&(c=5E-4>e?5E-7>e?b+6:b+4:b+2);c=Math.pow(10,c);a=Math.round(a*c)/c;return a.toString()};q.trn.a.q=function(a,b){if(!a)throw Error(b);};q.trn.a.ng=function(a){return(new q.trn.a(a)).Ae()};
q.trn.a.prototype={hd:function(a){return a+"."+q.trn.a.d[q.trn.a.cd]+"(t.m_a,t.m_b,t.m_c,t.m_d,t.m_h,t.m_v);"},ie:function(a){var b="oc"+this.sa,c="ox"+this.sa;this.b+="var "+b+"=document.createElement('canvas');";this.b+=b+".width=b[2]";this.b+=";"+b+".height=b[3]";this.b+=";";this.b+="var "+c+"="+b+".getContext('2d');";b="o"+this.sa;this.b+="var "+b+"=function(c,ob){";this.b+="c."+q.trn.a.d[q.trn.a.Vc]+"();";this.b+="c."+q.trn.a.d[q.trn.a.oc]+"(0,0);";this.b+="c."+q.trn.a.d[q.trn.a.ib]+"(b[2],0);";
this.b+="c."+q.trn.a.d[q.trn.a.ib]+"(b[2],b[3]);";this.b+="c."+q.trn.a.d[q.trn.a.ib]+"(0,b[3]);";this.b+="c."+q.trn.a.d[q.trn.a.Wc]+"();";this.b+="c."+q.trn.a.d[q.trn.a.Kb]+"(-b[0],-b[1]);";this.b+=this.hd("c");var e=this.kb(),f=this.c.p("RenderTransform");if(f!=h){var g=new q.trn.o;g.N(f);e.Aa(g)}this.b+=e.lb();this.b+=a;this.b+="};";this.b+=b+"("+c+",b);";return c},De:function(a){var b="t"+this.sa;this.b+=this.qd("var "+b+"=function(c,ob)");var c="tx"+this.sa;this.b+=a+".width=b[2];";this.b+=a+
".height=b[3];";this.b+="var "+c+"="+a+".getContext('2d');";a=this.kb();this.b+=c+"."+q.trn.a.d[q.trn.a.Kb]+"(-b[0],-b[1]);";this.b+=this.hd(c);this.b+=a.md(c);this.b+=b+"("+c+",b);";return c},mc:function(a){var b,c=this.ze(),e=this.c.A();q.trn.a.g(e,"Path")?b=this.rc():q.trn.a.g(e,"Canvas")?b=this.pc():q.trn.a.g(e,"Glyphs")?b=this.qc():(b=h,q.trn.a.q(l,"Invalid Element "+e));b.Ab(c);if(b.lf()){var c="m"+ ++this.sa,e="d"+this.sa,f="tc"+this.sa;this.b+="var b=["+q.trn.a.i(b.k)+","+q.trn.a.i(b.l)+","+
q.trn.a.i(b.k+b.t)+","+q.trn.a.i(b.l+b.s)+"];";this.b+="var x1=b[0]*t.m_a + b[1]*t.m_c + t.m_h;";this.b+="var y1=b[0]*t.m_b + b[1]*t.m_d + t.m_v;";this.b+="var x2=b[2]*t.m_a + b[3]*t.m_c + t.m_h;";this.b+="var y2=b[2]*t.m_b + b[3]*t.m_d + t.m_v;";this.b+="if(x1<x2){b[0]=Math.floor(x1);b[2]=Math.ceil(x2-x1);}else{b[2]=Math.ceil(x1-x2);b[0]=Math.floor(x2);}";this.b+="if(y1<y2){b[1]=Math.floor(y1);b[3]=Math.ceil(y2-y1);}else{b[3]=Math.ceil(y1-y2);b[1]=Math.floor(y2);}";this.b+="var "+f+"=document.createElement('canvas');";
b=this.De(f);a=this.ie(a);this.b+="var "+c+"="+a+"."+q.trn.a.d[q.trn.a.Zc]+"(0,0,b[2],b[3]);";this.b+="var "+e+"="+b+"."+q.trn.a.d[q.trn.a.Zc]+"(0,0,b[2],b[3]);";this.b+="var m = b[3]*b[2]<<2;";this.b+="for(var s=3;s<m;s+=4){";this.b+=e+".data[s]*=";this.b+=c+".data[s]/255;";this.b+="}";this.b+=b+"."+q.trn.a.d[q.trn.a.te]+"("+e+",0,0);";this.b+=this.O;this.b+="c."+q.trn.a.d[q.trn.a.xe]+"(1,0,0,1,b[0]-ob[0],b[1]-ob[1]);";this.b+="c."+q.trn.a.d[q.trn.a.Yc]+"("+f+",0,0);";this.b+=this.ja}else this.V=
l},pc:function(){var a=new q.trn.T;this.S();var b=this.c.p("RenderTransform");if(b!=h){var c=new q.trn.o;c.N(b);this.H(c)}b=this.c.p("Clip");b!=h&&(a=this.ra(b));b=h;if(!this.c.U()){for(this.c.u();this.c.advance();)c=this.c.A(),q.trn.a.g(c,"Canvas.Clip")?(q.trn.a.q(!this.c.U(),"Canvas.Clip: Must contain PathGeometry element"),this.c.u(),this.c.advance()&&(c=new q.trn.o,c.N(this.m("Transform")),this.H(c),a.Ab(this.ra(this.m("Figures"))),c=c.nb(),this.H(c)),this.c.r()):q.trn.a.g(c,"Path")?b!=h?b.Gc(this.rc()):
b=this.rc():q.trn.a.g(c,"Glyphs")?b!=h?b.Gc(this.qc()):b=this.qc():q.trn.a.g(c,"Canvas")&&(b!=h?b.Gc(this.pc()):b=this.pc());this.c.r()}b!=h&&a.Ab(b);this.ka();return a},Oe:function(){var a=this.zc();a||(this.b+=this.O,this.S());var b=h,c=this.c.p("OpacityMask");c!=h&&(b=this.Wa(c,d,"c."+q.trn.a.d[q.trn.a.Ua]+"();"));if(!this.c.U()){for(this.c.u();this.c.advance();)if(c=this.c.A(),q.trn.a.g(c,"Canvas.Resources"))this.c.U()?q.trn.a.q(l,"Canvas.Resources must contain ResourceDictionary element"):(this.c.u(),
this.c.advance(),this.Cd(),this.c.r());else if(q.trn.a.g(c,"Canvas.Clip"))q.trn.a.q(!this.c.U(),"Canvas.Clip: Must contain PathGeometry element"),this.c.u(),this.c.advance()&&(a||(this.b+=this.O,a=d,this.S()),c=new q.trn.o,c.N(this.m("Transform")),this.b+=this.H(c),q.trn.a.q(q.trn.a.g(this.c.A(),"PathGeometry"),"Path.Clip must contain PathGeometry"),this.Ub(this.m("Figures")),c=c.nb(),this.b+=this.H(c)),this.c.r();else if(q.trn.a.g(c,"Canvas.OpacityMask"))this.V?this.V=l:(this.c.u(),this.c.advance(),
b=this.Va("c."+q.trn.a.d[q.trn.a.ia],"c."+q.trn.a.d[q.trn.a.Ua]+"();",new q.trn.o),this.c.r(),this.V=d);else if(q.trn.a.g(c,"Path")||q.trn.a.g(c,"Glyphs")||q.trn.a.g(c,"Canvas")){if(b!=h){this.vb();this.c.r();this.V=d;this.mc(b);return}this.Ga=l;break}this.Ga&&this.c.r()}this.Ga&&this.vb()},vb:function(){this.b+=this.ja;this.ka()},Cb:function(a){a=this.c.p(a);q.trn.a.q(a!=h,this.c.A()+": "+a+" is not defined");return parseFloat(a)},qa:function(a,b){a=this.c.p(a);return a!=h?parseFloat(a):b},m:function(a){a=
this.c.p(a);q.trn.a.q(a!=h,this.c.A()+": "+a+" is not defined");return a},cb:function(a,b){a=this.c.p(a);return a!=h?a:b},Jd:function(){var a;a=this.c.p("x:Key");q.trn.a.q(a!=h,"Key must be defined for elements in a resource dictionary");return a},zc:function(){this.c.Zb();var a=l,b=this.qa("Opacity",1);1>b&&(a||(a=d,this.b+=this.O,this.S()),this.b+=this.Ta(b));b=this.c.p("RenderTransform");b!=h&&(a||(a=d,this.b+=this.O,this.S()),this.Ea(b)?this.b+=this.Mb(b):this.Ad(b));b=this.c.p("Clip");b!=h&&
(a||(this.b+=this.O,this.S()),this.Ub(b),a=d);return a},Ub:function(a){var b=d;a&&"F"===a[0]&&(b=l);this.Dd(b?"evenodd":"nonzero");this.Fe(this.ra(a));this.Ac(a);this.b+="c."+q.trn.a.d[q.trn.a.le]+"("+(b?"'evenodd'":"")+");"},Ne:function(a){var b=[];for(a=C.gb.Ma(a.split(";"));a.Od();){var c=a.Gd,e=new q.trn.Da,c=c.split(",");if(1<=c.length){if(0<c[0].length){var f=c[0].split(")");if(2<=f.length){var g=f[0].substr(1).split(":");e.tc=parseInt(g[0]);e.uc=parseInt(g[1])}e.Qb=parseInt(f[f.length-1]);
e.Sb=d}2<=c.length&&(0<c[1].length&&(e.sc=parseFloat(c[1]),e.wc=d),3<=c.length&&(0<c[2].length&&(e.Rb=parseFloat(c[2])),4<=c.length&&0<c[3].length&&(e.Tb=parseFloat(c[3]))))}b.add(e)}return b},Ee:function(){var a=this.m("UnicodeString"),b="",c=0,e=0,f=0,g=0;for(2<=a.length&&("{"===a.charAt(0)&&"}"===a.charAt(1))&&(a=a.substr(2));c<a.length;)e=a.charCodeAt(c),128>e?(b+=String.fromCharCode(e),c++):191<e&&224>e?(f=a.charCodeAt(c+1),b+=String.fromCharCode((e&31)<<6|f&63),c+=2):(f=a.charCodeAt(c+1),g=
a.charCodeAt(c+2),b+=String.fromCharCode((e&15)<<12|(f&63)<<6|g&63),c+=3);return b},qc:function(){var a=new q.trn.T,b=this.c.p("Clip");b!=h&&(a=this.ra(b));return a},Qe:function(){var a=this.zc(),b=this.Cb("OriginX"),c=this.Cb("OriginY"),e=this.m("FontUri");this.pb[e]=h;var f=this.Cb("FontRenderingEmSize"),g=this.Ne(this.cb("Indices",""));if(200>f){f/=200;a||(this.S(),this.b+=this.O,a=d);var k=new q.trn.o;k.mb(f,0,0,f,b,c);f=200;b=c=0;this.b+=k.lb()}for(var k=0,n="p"+ ++this.He,b="var "+n+"="+b+";",
m=this.Ee(),s=0,w=0,x=f/100,y="",Q=0;Q<g.length;++Q){var r=g[Q];if(s!==r.Rb||w!==r.Tb)y&&(b+="c."+q.trn.a.d[q.trn.a.nc]+'("'+q.trn.a.yb(y)+'",'+n+(s?"+"+q.trn.a.i(s*x):"")+","+q.trn.a.i(c-w*x)+");",b+=n+"+=c."+q.trn.a.d[q.trn.a.ad]+'("'+q.trn.a.yb(y)+'").'+q.trn.a.d[q.trn.a.ye]+";"),s=r.Rb,w=r.Tb,y="";r.wc?(b+="c."+q.trn.a.d[q.trn.a.nc]+'("'+q.trn.a.yb(y+(r.Sb?String.fromCharCode(r.Qb+57344):m.substr(k,1)))+'",'+n+(s?"+"+q.trn.a.i(s*x):"")+","+q.trn.a.i(c-w*x)+");",b+=n+"+=",y&&(b+="c."+q.trn.a.d[q.trn.a.ad]+
'("'+q.trn.a.yb(y)+'").width+'),b+=q.trn.a.i(r.sc*x)+";",y=""):y+=r.Sb?String.fromCharCode(r.Qb+57344):m.substr(k,1);Q+=r.uc-1;k+=r.tc}if(y||k<m.length)b+="c."+q.trn.a.d[q.trn.a.nc]+'("'+q.trn.a.yb(y+m.substr(k,m.length-k))+'",'+n+","+q.trn.a.i(c)+");";g=c=h;k=this.c.p("OpacityMask");k!=h&&(g=this.Wa(k,d,"c."+q.trn.a.d[q.trn.a.Ua]+"();"));if(!this.c.U()){for(this.c.u();this.c.advance();)k=this.c.A(),q.trn.a.g(k,"Glyphs.Clip")?(q.trn.a.q(!this.c.U(),"Canvas.Clip: Must contain PathGeometry element"),
this.c.u(),this.c.advance()&&(a||(a=d,this.b+=this.O,this.S()),k=new q.trn.o,k.N(this.m("Transform")),this.b+=k.lb(),q.trn.a.q(q.trn.a.g(this.c.A(),"PathGeometry"),"Path.Clip must contain PathGeometry"),n=this.m("Figures"),this.Ub(n),k=k.nb(),this.b+=k.lb()),this.c.r()):q.trn.a.g(k,"Glyphs.Fill")?(this.c.u(),this.c.advance(),c=this.Va("c."+q.trn.a.d[q.trn.a.ia],b,new q.trn.o),this.c.r()):q.trn.a.g(k,"Glyphs.OpacityMask")&&(this.V?this.V=l:(this.c.u(),this.c.advance(),g=this.Va("c."+q.trn.a.d[q.trn.a.ia],
"c."+q.trn.a.d[q.trn.a.Ua]+"();",new q.trn.o),this.c.r(),this.V=d));this.c.r()}g==h&&("otf"===e.substr(e.indexOf(".")+1)?(e=e.substr(0,e.length-4),e=parseInt(e.substr(7))):e=parseInt(e.substr(35,8),16),e="f"+e,Object.Ld(this.Ha,e)?10>this.Ha[e].length&&(this.Ha[e]+=m.substr(0,10-this.Ha[e].length)):this.Ha[e]=m.substr(0,10),this.Te(q.trn.a.i(f)+"px "+e),k=this.c.p("Fill"),k!=h&&(c=this.Ea(k)?this.Wa(k,d,b):this.Nb(k,"c."+q.trn.a.d[q.trn.a.ia],b)),c!=h&&(-1===c.indexOf(this.O)?this.Vb(c,b):this.Vb("c."+
q.trn.a.d[q.trn.a.ia]+"='#000000';"+b,b)));a&&(this.b+=this.ja,this.ka());g!=h&&(this.V=d,this.mc(g))},jd:function(){var a=new String;this.c.u();q.trn.a.q(this.c.advance(),"Gradient brushes must contain GradientStops");for(this.c.u();this.c.advance();)var b=this.m("Color"),c=this.m("Offset"),a=a+("g."+q.trn.a.d[q.trn.a.je]+"("+c+","+this.gd(b)+");");this.c.r();this.c.r();return a},ld:function(a,b,c){var e=this.c.p("Transform"),f=new String,f=f+this.O;this.S();e!=h&&(c.N(e),f+=this.H(c));c=this.qa("Opacity",
1);1>c&&(f+=this.Ta(c));c=this.m("StartPoint");e=this.m("EndPoint");f+="var g=c."+q.trn.a.d[q.trn.a.me]+"("+c+","+e+");";f+=this.jd();f=f+(a+"=g;")+b;f+=this.ja;this.ka();return f},nd:function(a,b,c){var e=this.c.p("Transform"),f=new String,g=this.m("RadiusX"),k=this.m("RadiusY"),n=this.m("GradientOrigin"),m=this.m("Center"),f=f+this.O;this.S();if(e!=h||g!==k)e!=h&&c.N(e),g!==k&&(e=parseFloat(g),k=parseFloat(k),q.trn.a.q(0<e&&0<k,"Invalid radius value"),k/=e,e=new q.trn.o,e.mb(1,0,0,k,0,0),c.Aa(e),
m=m.split(","),m=q.trn.a.i(parseFloat(m[0]))+","+q.trn.a.i(parseFloat(m[1])/k),n=n.split(","),n=q.trn.a.i(parseFloat(n[0]))+","+q.trn.a.i(parseFloat(n[1])/k)),f+=this.H(c);c=this.qa("Opacity",1);1>c&&(f+=this.Ta(c));f+="var g=c."+q.trn.a.d[q.trn.a.ne]+"("+n+",0,"+m+","+g+");";f+=this.jd();f=f+(a+"=g;")+b;f+=this.ja;this.ka();return f},Ye:function(a){var b=U(this.z);a!==b.bb?(N(a,"c."+q.trn.a.d[q.trn.a.Jb]+"='")&&(b.bb=a),this.b+=a):this.b+="c."+q.trn.a.d[q.trn.a.jb]+"();"},Vb:function(a,b){var c=
U(this.z);a!==c.Ya?(N(a,"c."+q.trn.a.d[q.trn.a.ia]+"='")&&(c.Ya=a),this.b+=a):this.b+=b},Ta:function(a){var b=U(this.z);b.Ia*=a;a=""+("c."+q.trn.a.d[q.trn.a.pe]+"=");a+=q.trn.a.i(b.Ia);return a+";"},Dd:function(a){var b=U(this.z);a!==b.Xa&&(b.Xa=a,this.b+='c.mozFillRule="'+a+'";')},We:function(a){var b=U(this.z);a!==b.Ka&&(b.Ka=a,this.b+="c."+q.trn.a.d[q.trn.a.$c]+"=",this.b+=q.trn.a.i(a),this.b+=";")},Ue:function(a){var b=U(this.z);a!==b.Za&&(b.Za=a,this.b+="c."+q.trn.a.d[q.trn.a.qe]+"='",this.b+=
a,this.b+="';")},Ve:function(a){var b=U(this.z);a!==b.Ja&&(b.Ja=a,this.b+="c."+q.trn.a.d[q.trn.a.re]+"='",this.b+=a,this.b+="';")},Xe:function(a){var b=U(this.z);a!==b.ab&&(b.ab=a,this.b+="c."+q.trn.a.d[q.trn.a.se]+"=",this.b+=q.trn.a.i(a),this.b+=";")},Te:function(a){var b=U(this.z);a!==b.rb&&(b.Ja=a,this.b+="c."+q.trn.a.d[q.trn.a.oe]+"='",this.b+=a,this.b+="';")},H:function(a){U(this.z).oa.Aa(a);return a.lb()},kb:function(){return U(this.z).oa},ze:function(){return U(this.z).da},Fe:function(a){U(this.z).da.Ab(a)},
S:function(){this.z.push(U(this.z).Bc());this.ba.add({})},ka:function(){this.z.pop();this.ba.Ec(this.ba.length-1)},kd:function(a,b,c){var e="",f=this.c.p("Transform"),e=e+this.O;this.S();var g=this.m("Viewbox"),k=new q.trn.T;k.Na(g);var g=this.m("Viewport"),n=new q.trn.T;n.Na(g);if(f!=h||k!==n){var g=n.t/k.t,m=n.s/k.s,s=n.k-k.k*g,k=n.l-k.l*m;f!=h&&(this.Ea(f)?e+=this.Mb(f):c.N(f));f=new q.trn.o;f.mb(g,0,0,m,s,k);c.Aa(f);e+=this.H(c)}c=this.qa("Opacity",1);1>c&&(e+=this.Ta(c));c=this.cb("TileMode",
"None");f=this.m("ImageSource");this.pb[f]=h;f="i"+parseInt(f.split("/")[2]);e=e+a+("=c."+q.trn.a.d[q.trn.a.Xc]+"(window.ci."+f+",");e="None"===c?e+"'no-repeat'":e+"'repeat'";e+=");";e+=b;e+=this.ja;this.ka();return e},Be:function(){var a="",b=this.c.p("Transform"),a=a+this.O;this.S();var c=this.m("Viewbox"),e=new q.trn.T;e.Na(c);var c=this.m("Viewport"),f=new q.trn.T;f.Na(c);if(b!=h||e!==f){var c=f.t/e.t,g=f.s/e.s,k=f.k-e.k*c,e=f.l-e.l*g,f=new q.trn.o;b!=h&&(this.Ea(b)?a+=this.Mb(b):f.N(b));b=new q.trn.o;
b.mb(c,0,0,g,k,e);f.Aa(b);a+=this.H(f)}b=this.qa("Opacity",1);1>b&&(a+=this.Ta(b));this.cb("TileMode","None");b=this.m("ImageSource");this.pb[b]=h;a+="c."+q.trn.a.d[q.trn.a.Yc]+"(window.ci."+("i"+parseInt(b.split("/")[2]))+", 0, 0);";a+=this.ja;this.ka();return a},Re:function(){this.Ad(this.c.p("Matrix"))},Ad:function(a){if(a!=h){var b=new q.trn.o;b.N(a);this.b+=this.H(b)}},h:function(a){for(var b=new String;","!==a.n.charAt(a.j)&&" "!==a.n.charAt(a.j)&&"\x00"!==a.n.charAt(a.j)&&!("E"!==a.n.charAt(a.j)&&
"e"!==a.n.charAt(a.j)&&("A"<=a.n.charAt(a.j)&&"Z">=a.n.charAt(a.j)||"a"<=a.n.charAt(a.j)&&"z">=a.n.charAt(a.j)));)b+=a.n.charAt(a.j),++a.j;for(;" "===a.n.charAt(a.j)||","===a.n.charAt(a.j);)++a.j;return parseFloat(b)},ra:function(a){var b=" ",c=new q.trn.Ib(a,0,h,0),e=new q.trn.T,f=d;e.zb(0,0,0,0);if(c.j<c.n.length)for(;" "===c.n.charAt(c.j);)c.j++;for(;c.j<a.length;){if("A"<=c.n.charAt(c.j)&&"Z">=c.n.charAt(c.j)||"a"<=c.n.charAt(c.j)&&"z">=c.n.charAt(c.j))b=c.n.charAt(c.j),c.j++;else{var g,k;"a">
b&&("H"!==b&&(c.f=0),"V"!==b&&(c.e=0));switch(b){case "m":case "M":c.e+=this.h(c);c.f+=this.h(c);f?(e.zb(c.e,c.f,c.e,c.f),f=l):e.W(c.e,c.f);c.D=l;break;case "l":case "L":c.e+=this.h(c);c.f+=this.h(c);e.W(c.e,c.f);c.D=l;break;case "c":case "C":g=this.h(c)+c.e;k=this.h(c)+c.f;e.W(g,k);c.D=d;c.$=this.h(c)+c.e;c.aa=this.h(c)+c.f;e.W(c.$,c.aa);c.e+=this.h(c);c.f+=this.h(c);e.W(c.e,c.f);break;case "q":case "Q":g=this.h(c)+c.e;k=this.h(c)+c.f;e.W(g,k);c.e+=this.h(c);c.f+=this.h(c);e.W(c.e,c.f);c.D=l;break;
case "s":case "S":c.D||(c.$=c.e,c.aa=c.f);g=2*c.e-c.$;k=2*c.f-c.aa;e.W(g,k);c.D=d;c.$=this.h(c)+c.e;c.aa=this.h(c)+c.f;e.W(c.$,c.aa);c.e+=this.h(c);c.f+=this.h(c);e.W(c.e,c.f);break;case "h":case "H":c.e+=this.h(c);e.W(c.e,c.f);c.D=l;break;case "v":case "V":c.f+=this.h(c);e.W(c.e,c.f);c.D=l;break;default:this.h(c),c.D=l}}for(;" "===a.charAt(c.j);)++c.j}return e.gf(this.kb())},rc:function(){var a=h;this.S();var b=this.c.p("RenderTransform");if(b!=h){var c=new q.trn.o;c.N(b);this.H(c)}b=this.c.p("Clip");
b!=h&&(a=this.ra(b));b=this.c.p("Data");if(!this.c.U()){for(this.c.u();this.c.advance();)if(c=this.c.A(),q.trn.a.g(c,"Path.Data")&&!this.c.U()){this.c.u();this.c.advance()&&(c=new q.trn.o,c.N(this.m("Transform")),this.H(c),q.trn.a.q(q.trn.a.g(this.c.A(),"PathGeometry"),"Path.Data must contain PathGeometry"),b=this.m("Figures"));this.c.r();break}else q.trn.a.g(c,"Path.Clip")&&(q.trn.a.q(!this.c.U(),"Path.Clip: Must contain PathGeometry element"),this.c.u(),this.c.advance()&&(c=new q.trn.o,c.N(this.m("Transform")),
this.H(c),a=this.ra(this.m("Figures")),c=c.nb(),this.H(c)),this.c.r());this.c.r()}a!=h?a.Ab(this.ra(b)):a=this.ra(b);this.ka();return a},ob:function(a,b,c){a.D=l;if(a.ea==h)this.b+="c."+q.trn.a.d[q.trn.a.ib]+"("+q.trn.a.i(a.e)+","+q.trn.a.i(a.f)+");";else for(var e=a.ea.length,f=a.e-b,g=a.f-c,k=g/f,n=Math.sqrt(f*f+g*g);1E-10<n;){var m=a.ea[a.Pb%e]-a.qb,s=m>n;s&&(a.qb+=n,m=n);if(f){var w=Math.sqrt(m*m/(1+k*k));0>f&&(w=-w);b+=w;c+=k*w}else c+=0<g?m:-m;this.b+="c."+(!(a.Pb%2)?q.trn.a.d[q.trn.a.ib]:q.trn.a.d[q.trn.a.oc])+
"("+q.trn.a.i(b)+","+q.trn.a.i(c)+");";n-=m;s||(++a.Pb,a.qb=0)}},Uc:function(a,b,c,e,f){a.D=d;if(a.ea==h)this.b+="c."+q.trn.a.d[q.trn.a.ke]+"("+q.trn.a.i(e)+","+q.trn.a.i(f)+","+q.trn.a.i(a.$)+","+q.trn.a.i(a.aa)+","+q.trn.a.i(a.e)+","+q.trn.a.i(a.f)+");";else{var g=this.kb().Cc(),g=g*((Math.abs(a.e-b)+Math.abs(a.f-c))/5),k=a.e,n=a.f;a.e=b;a.f=c;for(var g=1/parseInt(g),m=0;1>=m;m+=g){var s=1-m,w=a.e,x=a.f;a.e=s*s*s*b+3*s*s*m*e+3*s*m*m*a.$+m*m*m*k;a.f=s*s*s*c+3*s*s*m*f+3*s*m*m*a.aa+m*m*m*n;this.ob(a,
w,x)}}},ge:function(a){if(a.ea==h)this.b+="c."+q.trn.a.d[q.trn.a.Wc]+"();";else{var b=a.e,c=a.f;a.e=a.ud;a.f=a.vd;this.ob(a,b,c)}},Le:function(a){a.ud=a.e;a.vd=a.f;this.b+="c."+q.trn.a.d[q.trn.a.oc]+"("+q.trn.a.i(a.e)+","+q.trn.a.i(a.f)+");";a.D=l;a.Pb=a.vc;a.qb=a.ta},Pe:function(a,b){var c,e,f=a.e,g=a.f;"a">b&&("H"!==b&&(a.f=0),"V"!==b&&(a.e=0));switch(b){case "m":case "M":a.e+=this.h(a);a.f+=this.h(a);this.Le(a);break;case "l":case "L":a.e+=this.h(a);a.f+=this.h(a);this.ob(a,f,g);break;case "c":case "C":c=
this.h(a)+a.e;e=this.h(a)+a.f;a.$=this.h(a)+a.e;a.aa=this.h(a)+a.f;a.e+=this.h(a);a.f+=this.h(a);this.Uc(a,f,g,c,e);break;case "q":case "Q":c=this.h(a)+a.e;e=this.h(a)+a.f;a.e+=this.h(a);a.f+=this.h(a);this.b+="c."+q.trn.a.d[q.trn.a.ue]+"("+q.trn.a.i(c)+","+q.trn.a.i(e)+","+q.trn.a.i(a.e)+","+q.trn.a.i(a.f)+");";a.D=l;break;case "s":case "S":a.D||(a.$=a.e,a.aa=a.f);c=2*a.e-a.$;e=2*a.f-a.aa;a.D=d;a.$=this.h(a)+a.e;a.aa=this.h(a)+a.f;a.e+=this.h(a);a.f+=this.h(a);this.Uc(a,f,g,c,e);break;case "h":case "H":a.e+=
this.h(a);this.ob(a,f,g);a.D=l;break;case "v":case "V":a.f+=this.h(a);this.ob(a,f,g);a.D=l;break;default:this.h(a),a.D=l}},Ce:function(a){if("Flat"===a)return"butt";if("Square"===a)return"square";if("Round"===a||"Triangle"===a)return"round";q.trn.a.q(l,"Invalid line cap "+a);return""},Ac:function(a){this.Bd(a,h,0)},Bd:function(a,b,c){var e=" ";b=new q.trn.Ib(a,0,b,c);this.b+="c."+q.trn.a.d[q.trn.a.Vc]+"();";if(b.j<b.n.length)for(;" "===b.n.charAt(b.j);)b.j++;for(;b.j<a.length;){"A"<=b.n.charAt(b.j)&&
"Z">=b.n.charAt(b.j)||"a"<=b.n.charAt(b.j)&&"z">=b.n.charAt(b.j)?(e=b.n.charAt(b.j),("z"===b.n.charAt(b.j)||"Z"===b.n.charAt(b.j))&&this.ge(b),b.j++):this.Pe(b,e);for(;" "===a.charAt(b.j);)++b.j}},Se:function(){var a=this.c.p("Data"),b=d;a&&"F"===a[0]&&(b=l);var c="c."+q.trn.a.d[q.trn.a.Ua]+"("+(b?"'evenodd'":"")+");",e=l,f=this.zc(),g=this.c.p("Fill");g!=h&&(g=this.Ea(g)?this.Wa(g,d,c):this.Nb(g,"c."+q.trn.a.d[q.trn.a.ia],c));var k=h,n=0,m=this.c.p("Stroke");m!=h&&(m=this.Ea(m)?this.Wa(m,l,"c."+
q.trn.a.d[q.trn.a.jb]+"();"):this.Nb(m,"c."+q.trn.a.d[q.trn.a.Jb],"c."+q.trn.a.d[q.trn.a.jb]+"();"));var s=this.qa("StrokeThickness",1),w=h,x=this.c.p("OpacityMask");x!=h&&(w=this.Wa(x,d,"c."+q.trn.a.d[q.trn.a.Ua]+"();"));n=h;x=new q.trn.o;if(!this.c.U()){for(this.c.u();this.c.advance();){var y=this.c.A();q.trn.a.g(y,"Path.Clip")?(q.trn.a.q(!this.c.U(),"Path.Clip: Must contain PathGeometry element"),this.c.u(),this.c.advance()&&(f||(f=d,this.b+=this.O,this.S()),n=new q.trn.o,n.N(this.m("Transform")),
this.b+=this.H(n),q.trn.a.q(q.trn.a.g(this.c.A(),"PathGeometry"),"Path.Clip must contain PathGeometry"),y=this.m("Figures"),this.Ub(y),n=n.nb()),this.c.r()):q.trn.a.g(y,"Path.Data")&&!this.c.U()?(this.c.u(),this.c.advance()&&(a=new q.trn.o,a.N(this.m("Transform")),n!=h?n.Aa(a):n=a,this.b+=this.H(n),q.trn.a.q(q.trn.a.g(this.c.A(),"PathGeometry"),"Path.Data must contain PathGeometry"),a=this.m("Figures")),this.c.r()):q.trn.a.g(y,"Path.Fill")?(this.c.u(),this.c.advance(),w==h&&"ImageBrush"===this.c.A()&&
(e=d,this.b+=this.Be()),g=this.Va("c."+q.trn.a.d[q.trn.a.ia],c,new q.trn.o),this.c.r()):q.trn.a.g(y,"Path.OpacityMask")?this.V?this.V=l:(this.c.u(),this.c.advance(),w=this.Va("c."+q.trn.a.d[q.trn.a.ia],c,new q.trn.o),this.c.r(),this.V=d):q.trn.a.g(y,"Path.Stroke")&&(this.c.u(),this.c.advance(),m=this.Va("c."+q.trn.a.d[q.trn.a.Jb],"c."+q.trn.a.d[q.trn.a.jb]+"();",x),this.c.r())}this.c.r()}if(w==h&&!e){q.trn.a.q(a!=h,"Paths must have Data defined");e=this.c.p("StrokeDashArray");if(e!=h){e=e.split(" ");
k=Array(e.length);for(n=0;n<e.length;++n)k[n]=parseFloat(e[n])*s,k[n]||(k[n]=0.005)}this.Dd(b?"evenodd":"nonzero");n=this.qa("StrokeDashOffset",0);k!=h&&g!=h&&(this.Ac(a),g!=h&&this.Vb(g,c),g=h);this.Bd(a,k,n);g!=h&&this.Vb(g,c);m!=h&&(this.We(s/x.Cc()),this.Ue(this.Ce(this.cb("StrokeStartLineCap","Flat"))),this.Ve(this.cb("StrokeLineJoin","miter").toLowerCase()),this.Xe(this.qa("StrokeMiterLimit",10)),this.Ye(m))}f&&(this.b+=this.ja,this.ka());w!=h&&(this.V=d,this.mc(w))},gd:function(a){var b=1,
c=[255,255,255,255];if("#"===a.charAt(0)){if(7===a.length)return"'"+a+"'";var b="FF",e,f;q.trn.a.q(9===a.length,"Color "+a+" is invalid in a XOD file");b=a.substr(1,2);e=a.substr(3,2);f=a.substr(5,2);a=a.substr(7,2);b=parseInt(b,16)/255;c[0]=parseInt(e,16);c[1]=parseInt(f,16);c[2]=parseInt(a,16)}else"s"===a.charAt(0)?(e=a.split("#")[1].split(","),3<e.length?(b=parseFloat(e[0]),f=255*parseFloat(e[1]),c[0]=parseInt(0>f?0:255<f?255:f),f=255*parseFloat(e[2]),f=0>f?0:255<f?255:f,c[1]=parseInt(f),f=255*
parseFloat(e[3])):(f=255*parseFloat(e[0]),f=0>f?0:255<f?255:f,c[0]=parseInt(f),f=255*parseFloat(e[1]),f=0>f?0:255<f?255:f,c[1]=parseInt(f),f=255*parseFloat(e[2])),f=0>f?0:255<f?255:f,c[2]=parseInt(f)):q.trn.a.q(l,"Invalid color for a XOD file");return"'rgba("+c[0]+","+c[1]+","+c[2]+","+q.trn.a.i(b)+")'"},od:function(a,b){return this.Nb(this.m("Color"),a,b)},Nb:function(a,b,c){return b+"="+this.gd(a)+";"+c},Ob:function(a){return this.qd("var "+a+"=function(c)")},qd:function(a){this.Ga=l;var b=this.$a,
c=this.b;this.b="";this.$a=this.c.depth;this.z.push(U(this.z).mf());for(this.b+=a+"{";this.xc(););this.z.pop();this.b+="};";this.$a=b;a=this.b;this.b=c;return a},pd:function(a,b,c){var e="",f=this.m("Viewbox"),g=new q.trn.T;g.Na(f);var f=this.m("Viewport"),k=new q.trn.T;k.Na(f);var n=this.c.p("Transform"),e=e+this.O;this.S();if(n!=h||g!==k){var f=k.t/g.t,m=k.s/g.s,s=k.k-g.k*f,k=k.l-g.l*m;n!=h&&(this.Ea(n)?e+=this.Mb(n):c.N(n));n=new q.trn.o;n.mb(f,0,0,m,s,k);c.Aa(n);e+=this.H(c)}c=this.kb().Cc();
f=Math.min(g.t,g.s);e+="var a=asc(t)*"+q.trn.a.i(c)+";if(a*"+f+"<2)a=2/"+f+";";if(g.k||g.l)e+="c."+q.trn.a.d[q.trn.a.Kb]+"("+q.trn.a.i(g.k)+","+q.trn.a.i(g.l)+");";e+="c."+q.trn.a.d[q.trn.a.bd]+"(1/a,1/a);";c=this.qa("Opacity",1);1>c&&(e+=this.Ta(c));c=this.cb("TileMode","None");++this.tb;f="c"+this.tb;m="x"+this.tb;e=e+("var "+f+"=document.createElement('canvas');")+(f+".width=");e+=g.t;e+="*a;"+f+".height=";e+=g.s;e+="*a;";e+="var "+m+"="+f+".getContext('2d');";e+=m+"."+q.trn.a.d[q.trn.a.bd]+"(a,a);";
if(g.k||g.l)e+=m+"."+q.trn.a.d[q.trn.a.Kb]+"("+q.trn.a.i(-g.k)+","+q.trn.a.i(-g.l)+");";-1!==b.indexOf("c."+q.trn.a.d[q.trn.a.jb])&&(e+="c."+q.trn.a.d[q.trn.a.$c]+"=a*"+U(this.z).Ka+";");g=this.c.p("Visual");g=g!=h?this.jc(g):"v"+this.tb;if(!this.c.U()){for(this.c.u();this.c.advance();)s=this.c.A(),q.trn.a.g(s,"VisualBrush.Visual")&&(this.c.u(),q.trn.a.q(this.c.advance(),"VisualBrush.Visual must contain Canvas, Path or Glyphs element"),e+=this.Ob(g),this.c.r());this.c.r()}e+=g;e+="("+m+");";e+=a;
e+="=c."+q.trn.a.d[q.trn.a.Xc]+"("+f+",";e="None"===c?e+"'no-repeat'":e+"'repeat'";e+=");";e+=b;e+=this.ja;this.ka();return e},Ea:function(a){return"{"===a.charAt(0)},jc:function(a){var b=a.indexOf("StaticResource");q.trn.a.q(0<b,"Invalid resource reference: "+a);b+=15;a=a.substr(b,a.length-1-b);for(var b=h,c=this.ba.length-1;0<=c;--c)if(Object.Ld(this.ba[c],a)){b=this.ba[c][a];break}q.trn.a.q(b!=h,"Dictionary key "+a+" does not exist.");return b},Wa:function(a,b,c){return this.jc(a)+"(c,"+b+",'"+
c+"');"},Mb:function(a){return this.jc(a)+"(c);"},xc:function(){var a=d;if(this.Ga){if(this.c.depth===this.$a)return q.trn.a.g(this.c.A(),"Canvas")&&this.vb(),l;a=this.c.advance();if(!a){this.c.r();if(this.c.depth===this.$a)return q.trn.a.g(this.c.A(),"Canvas")&&this.vb(),l;this.vb();return d}}this.Ga=d;a=this.c.A();q.trn.a.g(a,"Canvas")?this.Oe():q.trn.a.g(a,"Path")?this.Se():q.trn.a.g(a,"Glyphs")&&this.Qe();return d},Lb:function(){var a=this.Jd(),b="r"+this.sb.toString();++this.sb;return this.ba[this.ba.length-
1][a]=b},Tc:function(){var a=this.Lb();this.b+="var "+a+"=function(c){\n"},hb:function(){var a=this.Jd(),b="r"+this.sb.toString();++this.sb;this.ba[this.ba.length-1][a]=b;this.b+="var "+b+"=function(c,s,o){"},Ba:function(){this.b+="};"},Va:function(a,b,c){var e=this.c.A();if(q.trn.a.g(e,"ImageBrush"))return this.kd(a,b,c);if(q.trn.a.g(e,"VisualBrush"))return this.pd(a,b,c);if(q.trn.a.g(e,"LinearGradientBrush"))return this.ld(a,b,c);if(q.trn.a.g(e,"RadialGradientBrush"))return this.nd(a,b,c);if(q.trn.a.g(e,
"SolidColorBrush"))return this.od(a,b);q.trn.a.q(l,"Invalid Brush Type: "+e);return""},Cd:function(){var a=this.c.A();if(q.trn.a.g(a,"ResourceDictionary")&&!this.c.U()){var b="c[(s?'"+q.trn.a.d[q.trn.a.ia]+"':'"+q.trn.a.d[q.trn.a.Jb]+"')]";for(this.c.u();this.c.advance();)a=this.c.A(),q.trn.a.g(a,"ImageBrush")?(this.hb(),this.b+=this.kd(b,"eval(o);"),this.Ba()):q.trn.a.g(a,"LinearGradientBrush")?(this.hb(),this.b+=this.ld(b,"eval(o);"),this.Ba()):q.trn.a.g(a,"RadialGradientBrush")?(this.hb(),this.b+=
this.nd(b,"eval(o);"),this.Ba()):q.trn.a.g(a,"VisualBrush")?(this.hb(),this.b+=this.pd(b,"eval(o);"),this.Ba()):q.trn.a.g(a,"SolidColorBrush")?(this.hb(),this.b+=this.od(b,"eval(o);"),this.Ba()):q.trn.a.g(a,"MatrixTransform")?(this.Tc(),this.Re(),this.Ba()):q.trn.a.g(a,"PathGeometry")?(this.Tc(),this.Ac(this.m("Figures")),this.Ba()):q.trn.a.g(a,"Path")?(a=this.Lb(),this.b+=this.Ob(a)):q.trn.a.g(a,"Glyphs")?(a=this.Lb(),this.b+=this.Ob(a)):q.trn.a.g(a,"Canvas")?(a=this.Lb(),this.b+=this.Ob(a)):q.trn.a.q(l,
"Resource type is invalid: "+a);this.c.r()}},Ae:function(){for(var a="";!this.Wb;)a+=this.Pd();return a},Pd:function(){this.b+="var ob=[0,0];";for(this.pb={};this.b.length<this.td&&this.xc(););this.xc()||(this.Wb=d);var a=this.b;this.b="";return a},df:function(){var a=[],b=this.pb,c;for(c in b)a.add(c.substr(1));return a},Wb:l,Ga:l,O:h,ja:h,V:l,b:h,xd:0,wd:0,sb:0,tb:0,sa:0,He:0,td:0,Ha:h,pb:h,$a:0,ba:h,z:h,c:h};
q.trn.Da=function(){this.wc=this.Sb=l;this.tc=this.uc=1;this.sc=this.Rb=this.Tb=this.Qb=0};q.trn.Da.prototype={Sb:l,wc:l,tc:0,uc:0,Qb:0,sc:0,Rb:0,Tb:0};q.trn.Ca=p();q.trn.Ca.jf=function(a,b){var c=new q.trn.Ca;c.bb="black";c.Ya="black";c.Xa="nonzero";c.Ia=1;c.Ka=1;c.Za="butt";c.Ja="miter";c.ab=10;c.rb="10px sans-serif";c.oa=new q.trn.o;c.da=new q.trn.T;c.da.zb(0,0,a,b);return c};
q.trn.Ca.prototype={Bc:function(){var a=new q.trn.Ca;a.bb=this.bb;a.Ya=this.Ya;a.Xa=this.Xa;a.Ia=this.Ia;a.Ka=this.Ka;a.Za=this.Za;a.Ja=this.Ja;a.ab=this.ab;a.rb=this.rb;a.oa=new q.trn.o;a.oa.rd(this.oa);a.da=new q.trn.T;a.da.zb(this.da.k,this.da.l,this.da.t,this.da.s);return a},mf:function(){var a=new q.trn.Ca;a.bb="black";a.Ya="black";a.Xa="nonzero";a.Ia=1;a.Ka=1;a.Za="butt";a.Ja="miter";a.ab=10;a.rb="10px sans-serif";a.oa=new q.trn.o;a.oa.rd(this.oa);a.da=new q.trn.T;return a},bb:h,Ya:h,Xa:h,Ia:0,
Ka:0,Za:h,Ja:h,ab:0,rb:h,oa:h,da:h};q.trn.Ra=function(a,b){this.x=a;this.y=b};q.trn.Ra.prototype={x:0,y:0};q.trn.T=function(){this.l=this.k=-1E6;this.t=this.s=2E6};
q.trn.T.prototype={zb:function(a,b,c,e){this.k=a;this.l=b;this.t=c;this.s=e},lf:function(){return 0<this.t&&0<this.s},Na:function(a){a=a.split(",");q.trn.a.q(4===a.length,"Rectangles should contain 4 numbers");this.k=parseFloat(a[0]);this.l=parseFloat(a[1]);this.t=parseFloat(a[2]);this.s=parseFloat(a[3])},gf:function(a){if(a.sd())return this;var b=new q.trn.Ra(this.k,this.l),c=new q.trn.Ra(this.k,this.l+this.s),e=new q.trn.Ra(this.k+this.t,this.l),f=new q.trn.Ra(this.k+this.t,this.l+this.s);a.$b(b);
a.$b(c);a.$b(e);a.$b(f);a=Math.min(b.x,c.x,e.x,f.x);var g=Math.max(b.x,c.x,e.x,f.x),k=Math.min(b.y,c.y,e.y,f.y),b=Math.max(b.y,c.y,e.y,f.y),c=new q.trn.T;c.zb(a,k,g-a,b-k);return c},W:function(a,b){a<this.k?(this.t+=this.k-a,this.k=a):a>this.k+this.t&&(this.t=a-this.k);b<this.l?(this.s+=this.l-b,this.l=b):b>this.l+this.s&&(this.s=b-this.l)},Gc:function(a){this.W(a.k,a.l);this.W(a.k+a.t,a.l+a.s)},Ab:function(a){var b,c,e,f,g,k,n;b=this.k;c=this.k+this.t;e=this.l;f=this.l+this.s;g=a.k;k=a.k+a.t;n=a.l;
a=a.l+a.s;if(c<g||k<b||f<n||a<e)this.k=this.t=this.l=this.s=0;else if(this.k=b<g?g:b,this.t=(c<k?c:k)-this.k,this.l=e<n?n:e,this.s=(f<a?f:a)-this.l,!this.t||!this.s)this.k=this.t=this.l=this.s=0},k:0,l:0,t:0,s:0};q.trn.o=function(){this.I=this.L=1;this.J=this.K=this.Q=this.R=0};
q.trn.o.prototype={I:0,J:0,K:0,L:0,Q:0,R:0,N:function(a){var b=[1,0,0,1,0,0];a=a.split(",");for(var c=0;c<a.length&&6>c;++c)b[c]=parseFloat(a[c]);this.I=b[0];this.J=b[1];this.K=b[2];this.L=b[3];this.Q=b[4];this.R=b[5]},mb:function(a,b,c,e,f,g){this.I=a;this.J=b;this.K=c;this.L=e;this.Q=f;this.R=g},rd:function(a){this.I=a.I;this.J=a.J;this.K=a.K;this.L=a.L;this.Q=a.Q;this.R=a.R},Aa:function(a){var b=this.I,c=this.J,e=this.K,f=this.L;this.I=a.I*b+a.J*e;this.J=a.I*c+a.J*f;this.K=a.K*b+a.L*e;this.L=a.K*
c+a.L*f;this.Q=a.Q*b+a.R*e+this.Q;this.R=a.Q*c+a.R*f+this.R},nb:function(){var a=new q.trn.o,b=this.I*this.L-this.J*this.K;if(!b)return a;a.I=this.L/b;a.K=-this.K/b;a.Q=(this.K*this.R-this.Q*this.L)/b;a.J=-this.J/b;a.L=this.I/b;a.R=-(this.I*this.R-this.Q*this.J)/b;return a},$b:function(a){var b=a.x*this.J+a.y*this.L+this.R;a.x=a.x*this.I+a.y*this.K+this.Q;a.y=b},Cc:function(){var a=0.707106781*this.I+0.707106781*this.J,b=0.707106781*this.K+0.707106781*this.L;return Math.sqrt(a*a+b*b)},sd:function(){return 1===
this.I&&!this.J&&!this.K&&1===this.L&&!this.Q&&!this.R?d:l},lb:function(){return this.md("c")},md:function(a){return this.sd()?"":a+"."+q.trn.a.d[q.trn.a.cd]+"("+q.trn.a.xb(this.I,4)+","+q.trn.a.xb(this.J,4)+","+q.trn.a.xb(this.K,4)+","+q.trn.a.xb(this.L,4)+","+q.trn.a.i(this.Q)+","+q.trn.a.i(this.R)+");"}};
q.trn.Ib=function(a,b,c,e){this.n=a;this.j=b;this.e=this.f=0;this.D=l;this.ea=c;if(this.ea!=h){for(b=a=0;b<this.ea.length;++b)a+=this.ea[b];this.ta=e%a;0>this.ta&&(this.ta+=a);for(b=this.vc=0;this.ta>this.ea[b];++b)this.ta-=this.ea[b],++this.vc}};q.trn.Ib.prototype={n:h,j:0,ea:h,Pb:0,qb:0,vc:0,ta:0,e:0,f:0,ud:0,vd:0,D:l,$:0,aa:0};q.trn.yd=function(a,b,c){this.Je=a;this.Ke=b;this.Ie=c};q.trn.yd.prototype={Ie:0,Ke:0,Je:0};q.trn.a.M("myglobs.trn.Converter");q.trn.Da.M("myglobs.trn._index");q.trn.Ca.M("myglobs.trn._gState");
q.trn.Ra.M("myglobs.trn.Point");q.trn.T.M("myglobs.trn._rect");q.trn.o.M("myglobs.trn._matrix2D");q.trn.Ib.M("myglobs.trn._abbrGeomItr");q.trn.yd.M("myglobs.trn._pageInfo");q.trn.a.Hf="http://schemas.microsoft.com/xps/2005/06/resourcedictionary-key";q.trn.a.Lf="http://schemas.openxps.org/oxps/v1.0/resourcedictionary-key";q.trn.a.Tf="http://schemas.microsoft.com/winfx/2006/xaml";q.trn.a.Ze="http://schemas.microsoft.com/xps/2005/06";q.trn.a.Uf="http://schemas.microsoft.com/winfx/2006/xaml/presentation";
q.trn.a.Mf="http://schemas.openxps.org/oxps/v1.0";q.trn.a.Wf="http://schemas.microsoft.com/xps/2005/06/documentstructure";q.trn.a.Kf="http://schemas.openxps.org/oxps/v1.0/documentstructure";q.trn.a.Qf="http://schemas.openxmlformats.org/package/2006/relationships";q.trn.a.Cf="http://schemas.openxmlformats.org/package/2006/content-types";q.trn.a.If="http://schemas.openxmlformats.org/markup-compatibility/2006";q.trn.a.Df="http://schemas.openxmlformats.org/package/2006/metadata/core-properties";
q.trn.a.Ef="http://purl.org/dc/elements/1.1/";q.trn.a.Ff="http://purl.org/dc/terms/";q.trn.a.Vf="http://www.w3.org/XML/1998/namespace";q.trn.a.Rf="clr-namespace:PDFTron.SilverDox.Internal;assembly=SilverDox";q.trn.a.Xf="http://schemas.microsoft.com/xps/2005/06/restricted-font";q.trn.a.Nf="http://schemas.openxps.org/oxps/v1.0/restricted-font";q.trn.a.Jf="application/vnd.ms-package.obfuscated-opentype";q.trn.a.Of="http://www.pdftron.com/silverdox/2010/09";q.trn.a.we=0;q.trn.a.ve=1;q.trn.a.cd=2;
q.trn.a.Kb=3;q.trn.a.$c=4;q.trn.a.qe=5;q.trn.a.Jb=6;q.trn.a.ia=7;q.trn.a.pe=8;q.trn.a.me=9;q.trn.a.ne=10;q.trn.a.Xc=11;q.trn.a.je=12;q.trn.a.Vc=13;q.trn.a.Wc=14;q.trn.a.Ua=15;q.trn.a.jb=16;q.trn.a.le=17;q.trn.a.oc=18;q.trn.a.ib=19;q.trn.a.ue=20;q.trn.a.ke=21;q.trn.a.oe=22;q.trn.a.nc=23;q.trn.a.ad=24;q.trn.a.ye=25;q.trn.a.se=26;q.trn.a.re=27;q.trn.a.Yc=28;q.trn.a.xe=29;q.trn.a.Zc=30;q.trn.a.te=31;q.trn.a.bd=32;q.trn.a.d="SrtTwcsfaLRPAbzFXCMlqBnxmWijIZdDe".split("");self.trn.a||(self.trn=trn);function Z(a){this.v="";this.rf=new self.Sa.gc(a);this.lg=l;$(this);this.start=0}Z.prototype={Ed:102400,Zb:function(a){var b=a-this.start;b>Z.prototype.Ed&&(this.v=this.v.slice(b),this.start=a)},indexOf:function(a,b){var c;b-=this.start;do c=this.v.indexOf(a,b);while(-1===c&&$(this));return c+this.start},charAt:function(a){a-=this.start;a>=this.v.length&&$(this);return this.v.charAt(a)},substring:function(a,b){a-=this.start;b-=this.start;return this.v.substring(a,b)}};
function $(a){var b=a.rf.Id(Z.prototype.Ed);return b.length?(a.v+=b,d):l}self.$d=Z;
self.onmessage=function(a){switch(a.data.command){case "data":a=new self.ce(new self.$d(a.data.dataString));self.wb=new self.trn.a(a);break;case "nextChunk":self.wb.Wb?(self.postMessage({command:"done"}),self.wb=h):(a=self.wb.Pd(),self.postMessage({command:"nextChunk",resources:self.wb.df(),dataString:a}));break;case "cancel":self.wb=h;self.postMessage({command:"done"});break;default:throw Error("Unknown message command "+a.data.command);}};
